# -*- coding: utf-8 -*-
"""kata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-0cTGQf5KmijbL02_LSz-XTG8xvjOELp
"""

!pip install opencv-python-headless

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

video_path = '/content/VID-20250515-WA0000.mp4'

lower_hsv = np.array([0, 0, 60])
upper_hsv = np.array([50, 60, 255])

cap = cv2.VideoCapture(video_path)

frame_count = 0
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    frame_count += 1


    frame = cv2.resize(frame, (640, 480))


    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)


    mask = cv2.inRange(hsv, lower_hsv, upper_hsv)


    kernel = np.ones((5,5), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)


    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    for cnt in contours:
        area = cv2.contourArea(cnt)
        if area > 2000:
            x, y, w, h = cv2.boundingRect(cnt)
            cv2.rectangle(frame, (x, y), (x+w, y+h), (0,255,0), 2)
            cv2.putText(frame, 'Bhara Katta', (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)


    if frame_count % 30 == 0:
        print(f"Frame {frame_count}")
        cv2_imshow(frame)

cap.release()
cv2.destroyAllWindows()